---
- hosts: nexus
  become: yes
  gather_facts: False
  tasks:
  
  - name: Patch update
    shell: yum -y update

  - name: Install EPEL-release
    yum: name=epel-release state=present

  - name: Install java_1.8
    yum: name=java-1.8.0-openjdk.x86_64 state=present

  - name: Install wget
    yum: name=wget state=present

  - name: Install rsync
    yum: name=rsync state=present

  - name: Creat nexus directory
    shell: |
      mkdir -p /opt/nexus
      mkdir -p /tmp/nexus
  - name: Download latest nexus latest tarball
    shell: |
      cd /tmp/nexus 
      wget https://download.sonatype.com/nexus/3/latest-unix.tar.gz -O nexus.tar.gz

  - name: Extrsact tar file
    shell: |
      cd /tmp/nexus
      EXTOUT=`tar xzvf nexus.tar.gz`
      NEXUSDIR=`echo $EXTOUT | cut -d '/' -f1`
      rm -rf /tmp/nexus/nexus.tar.gz

  - name: sync /tmp/nexus/ and /opt/nexus/
    shell: rsync -avzh /tmp/nexus/ /opt/nexus/

  - name: Add nexus user
    shell:  |
      useradd nexus
      chown -R nexus.nexus /opt/nexus 

  - name: Create nexus service
    shell: |
      cat <<EOT>> /etc/systemd/system/nexus.service
      [Unit]                                                                          
      Description=nexus service                                                       
      After=network.target                                                            
                                                                        
      [Service]                                                                       
      Type=forking                                                                    
      LimitNOFILE=65536                                                               
      ExecStart=/opt/nexus/$NEXUSDIR/bin/nexus start                                  
      ExecStop=/opt/nexus/$NEXUSDIR/bin/nexus stop                                    
      User=nexus                                                                      
      Restart=on-abort                                                                
                                                                        
      [Install]                                                                       
      WantedBy=multi-user.target                                                      
      EOT

  - name: Creasting nexus.rc
    shell: echo 'run_as_user="nexus"' > /opt/nexus/$NEXUSDIR/bin/nexus.rc

  - name: Reeload daemon, Start and enable nexus
    shell: |
      systemctl daemon-reload
      systemctl start nexus
      systemctl enable nexus